[package]
name = "wasm-split"
version = "0.4.2"
authors = ["Sentry <hello@getsentry.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
hex = "0.4.2"
uuid = { version = "0.8.2", features = ["v4"] }
wasmbin = "0.3.1"