os: linux
dist: xenial
language: rust

before_install:
  - pyenv install 3.6.3
  - pyenv global 3.6.3

git:
  depth: 1

branches:
  only:
    - master
    - /^release\/[\d.]+$/
    - /^deploy\/.*$/

jobs:
  include:
    - name: "style check"
      script: make -e style

    - name: "lint"
      script: make -e lint

    - name: "test"
      script: make -e test-rust

    - name: "e2e"
      script: make -e test-integration

    - name: "docs"
      before_script: npm install -g @zeus-ci/cli
      script: make -e travis-upload-docs

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/53a70baa-5131-11e9-902b-0a580a282506/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
