[package]
name = "symbolicator-crash"
authors = ["Sentry <oss@sentry.io>"]
description = "Native crash reporting for Symbolicator"
homepage = "https://getsentry.github.io/symbolicator/"
repository = "https://github.com/getsentry/symbolicator"
version = "23.9.1"
edition = "2018"
build = "build.rs"
license-file = "../LICENSE"
publish = false

[dependencies]

[build-dependencies]
bindgen = "0.66.1"
cmake = { version = "0.1.46" }
